# Generated by Django 5.2 on 2025-05-05 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='icon_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('artist', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(null=True, upload_to='cover_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
