# Generated by Django 5.2 on 2025-05-10 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='cover_images/'),
        ),
    ]
