# Generated by Django 5.2 on 2025-05-10 13:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0002_alter_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='icon_images/'),
        ),
    ]
