# Generated by Django 5.2 on 2025-05-28 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0003_alter_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
